# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('land_take_off_price', models.FloatField()),
                ('noise_price', models.FloatField()),
                ('park_price', models.FloatField()),
                ('fuel_cost', models.FloatField()),
                ('cargo_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(max_length=250)),
                ('contents', models.CharField(max_length=250)),
                ('dest_air_port', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='est_air_port', to='courier_mb.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_mb.PackageType'),
        ),
        migrations.AddField(
            model_name='package',
            name='post_air_port',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_air_port', to='courier_mb.Airport'),
        ),
    ]
