# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_mb', '0002_auto_20170616_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('DE', 'Delivered'), ('WAIT', 'Waiting'), ('OTW', 'On the way')], default='WAIT', max_length=10),
        ),
    ]
